# Generated by Django 4.2.7 on 2023-12-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_productinstance_industry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productindustry'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='unit_of_measure',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('TON', 'Ton'), ('G', 'Gram'), ('LB', 'Pound'), ('L', 'Liter'), ('ML', 'Milliliter'), ('M3', 'Cubic Meter'), ('CM3', 'Cubic Centimeter'), ('EA', 'Each'), ('DOZ', 'Dozen'), ('M', 'Meter'), ('CM', 'Centimeter'), ('INCH', 'Inch')], max_length=50),
        ),
    ]
