# Generated by Django 4.2.7 on 2023-12-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productinstance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinstance',
            unique_together={('product', 'company')},
        ),
    ]
