# Generated by Django 4.2.7 on 2024-01-26 16:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_productinstance_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='user',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='contact_email',
            new_name='member_contact_email',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_name',
            new_name='member_identification',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='identification',
            new_name='member_job_title',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, choices=[(1, 'United States'), (2, 'Mexico'), (3, 'Brazil'), (4, 'Colombia'), (5, 'Argentina'), (6, 'Canada'), (7, 'Peru'), (8, 'Venezuela'), (9, 'Chile'), (10, 'Guatemala'), (11, 'Ecuador'), (12, 'Cuba'), (13, 'Bolivia'), (14, 'Dominican Republic'), (15, 'Honduras'), (16, 'Paraguay'), (17, 'El Salvador'), (18, 'Nicaragua'), (19, 'Costa Rica'), (20, 'Puerto Rico'), (21, 'Panama'), (22, 'Uruguay'), (23, 'Jamaica'), (24, 'Trinidad and Tobago'), (25, 'Guyana'), (26, 'Suriname'), (27, 'Belize'), (28, 'Barbados'), (29, 'Saint Lucia'), (30, 'Grenada'), (31, 'Antigua and Barbuda'), (32, 'Saint Vincent and the Grenadines'), (33, 'Saint Kitts and Nevis'), (34, 'Bahamas'), (35, 'Bermuda'), (36, 'Anguilla'), (37, 'Turks and Caicos Islands'), (38, 'Cayman Islands'), (39, 'Montserrat'), (40, 'British Virgin Islands'), (41, 'United Kingdom'), (42, 'Germany'), (43, 'France'), (44, 'Spain'), (45, 'Italy'), (46, 'Netherlands'), (47, 'Belgium'), (48, 'Portugal'), (49, 'Switzerland'), (50, 'Austria'), (51, 'Sweden'), (52, 'Poland'), (53, 'Norway'), (54, 'Denmark'), (55, 'Finland'), (56, 'Greece'), (57, 'Ireland'), (58, 'Czech Republic'), (59, 'Hungary'), (60, 'Romania'), (61, 'Bulgaria'), (62, 'Croatia'), (63, 'Slovakia'), (64, 'Slovenia'), (65, 'Lithuania'), (66, 'Latvia'), (67, 'Estonia'), (68, 'Cyprus'), (69, 'Luxembourg'), (70, 'Malta'), (71, 'Iceland'), (72, 'Liechtenstein'), (73, 'Monaco'), (74, 'San Marino'), (75, 'Andorra'), (76, 'Vatican City'), (77, 'Australia'), (78, 'South Africa'), (79, 'New Zealand'), (80, 'India'), (81, 'Nigeria'), (82, 'Pakistan'), (83, 'Bangladesh'), (84, 'Philippines'), (85, 'Egypt'), (86, 'Turkey'), (87, 'Indonesia'), (88, 'Vietnam'), (89, 'Thailand'), (90, 'South Korea'), (91, 'Japan'), (92, 'China'), (93, 'Russia'), (94, 'Saudi Arabia'), (95, 'Iran'), (96, 'Iraq'), (97, 'United Arab Emirates'), (98, 'Qatar'), (99, 'Kuwait'), (100, 'Oman'), (101, 'Lebanon'), (102, 'Jordan'), (103, 'Israel'), (104, 'Palestine'), (105, 'Syria'), (106, 'Yemen'), (107, 'Bahrain'), (108, 'Afghanistan'), (109, 'Pakistan'), (110, 'Mongolia'), (111, 'Kazakhstan'), (112, 'Uzbekistan'), (113, 'Turkmenistan'), (114, 'Kyrgyzstan'), (115, 'Tajikistan'), (116, 'Georgia'), (117, 'Armenia'), (118, 'Azerbaijan'), (119, 'Belarus'), (120, 'Ukraine'), (121, 'Moldova'), (122, 'Serbia'), (123, 'Montenegro'), (124, 'Kosovo'), (125, 'North Macedonia'), (126, 'Albania'), (127, 'Bosnia and Herzegovina'), (128, 'Croatia'), (129, 'Slovenia'), (130, 'Kosovo'), (131, 'North Macedonia'), (132, 'Serbia'), (133, 'Montenegro'), (134, 'Bosnia and Herzegovina'), (135, 'Croatia'), (136, 'Slovenia'), (137, 'North Korea'), (138, 'Mauritius'), (139, 'Maldives'), (140, 'Fiji'), (141, 'Papua New Guinea'), (142, 'Solomon Islands'), (143, 'Vanuatu'), (144, 'Samoa'), (145, 'Tonga'), (146, 'Kiribati'), (147, 'Tuvalu'), (148, 'Nauru'), (149, 'Palau'), (150, 'Marshall Islands'), (151, 'Micronesia'), (152, 'Comoros'), (153, 'Seychelles'), (154, 'Cabo Verde'), (155, 'Timor-Leste'), (156, 'Brunei'), (157, 'Bhutan'), (158, 'Sao Tome and Principe'), (159, 'Saint Kitts and Nevis'), (160, 'Antigua and Barbuda'), (161, 'Saint Vincent and the Grenadines'), (162, 'Saint Lucia'), (163, 'Grenada'), (164, 'Dominica'), (165, 'Saint Pierre and Miquelon'), (166, 'Faroe Islands'), (167, 'Greenland'), (168, 'Aruba'), (169, 'Curaçao'), (170, 'Sint Maarten'), (171, 'Bonaire'), (172, 'Saba'), (173, 'Sint Eustatius'), (174, 'South Georgia and the South Sandwich Islands'), (175, 'Christmas Island'), (176, 'Cocos (Keeling) Islands'), (177, 'Norfolk Island'), (178, 'Niue'), (179, 'Tokelau'), (180, 'Cook Islands'), (181, 'Pitcairn Islands'), (182, 'Anguilla'), (183, 'Montserrat'), (184, 'Turks and Caicos Islands'), (185, 'British Virgin Islands'), (186, 'Cayman Islands'), (187, 'Bermuda'), (188, 'Guernsey'), (189, 'Jersey'), (190, 'Isle of Man'), (191, 'Åland Islands'), (192, 'Svalbard and Jan Mayen'), (193, 'French Southern and Antarctic Lands'), (194, 'Mayotte'), (195, 'Réunion'), (196, 'French Guiana'), (197, 'Martinique'), (198, 'Guadeloupe'), (199, 'Clipperton Island'), (200, 'French Polynesia'), (201, 'New Caledonia'), (202, 'Wallis and Futuna'), (203, 'French Southern and Antarctic Lands'), (204, 'Mayotte'), (205, 'Réunion'), (206, 'French Guiana'), (207, 'Martinique'), (208, 'Guadeloupe'), (209, 'Clipperton Island'), (210, 'French Polynesia'), (211, 'New Caledonia'), (212, 'Wallis and Futuna'), (213, 'French Southern and Antarctic Lands'), (214, 'Mayotte'), (215, 'Réunion'), (216, 'French Guiana'), (217, 'Martinique'), (218, 'Guadeloupe'), (219, 'Clipperton Island'), (220, 'French Polynesia'), (221, 'New Caledonia'), (222, 'Wallis and Futuna'), (223, 'French Southern and Antarctic Lands'), (224, 'Mayotte'), (225, 'Réunion'), (226, 'French Guiana'), (227, 'Martinique'), (228, 'Guadeloupe'), (229, 'Clipperton Island'), (230, 'French Polynesia'), (231, 'New Caledonia'), (232, 'Wallis and Futuna'), (233, 'French Southern and Antarctic Lands'), (234, 'Mayotte'), (235, 'Réunion'), (236, 'French Guiana'), (237, 'Martinique'), (238, 'Guadeloupe'), (239, 'Clipperton Island'), (240, 'French Polynesia'), (241, 'New Caledonia'), (242, 'Wallis and Futuna'), (243, 'French Southern and Antarctic Lands'), (244, 'Mayotte'), (245, 'Réunion'), (246, 'French Guiana'), (247, 'Martinique'), (248, 'Guadeloupe'), (249, 'Clipperton Island'), (250, 'French Polynesia'), (251, 'New Caledonia'), (252, 'Wallis and Futuna'), (253, 'French Southern and Antarctic Lands'), (254, 'Mayotte'), (255, 'Réunion')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='member_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/profile.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, default='/profile.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='image',
            field=models.ImageField(blank=True, default='/profile.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProductIndustry',
        ),
    ]
