# Generated by Django 4.2.7 on 2024-02-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_company_district_company_factura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizationlog',
            old_name='quantity',
            new_name='amount',
        ),
    ]
