# Generated by Django 4.2.7 on 2024-02-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_customuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
