export const BASE_URL = 'http://127.0.0.1:8000'

export const countryCodes = [
      { code: '+1', name: 'United States' },
      { code: '+51', name: 'Peru' },
      { code: '+52', name: 'Mexico' },
      { code: '+53', name: 'Cuba' },
      { code: '+54', name: 'Argentina' },
      { code: '+55', name: 'Brazil' },
      { code: '+56', name: 'Chile' },
      { code: '+57', name: 'Colombia' },
      { code: '+58', name: 'Venezuela' },
      { code: '+60', name: 'Malaysia' },
      { code: '+61', name: 'Australia' },
      { code: '+62', name: 'Indonesia' },
      { code: '+63', name: 'Philippines' },
      { code: '+64', name: 'New Zealand' },
      { code: '+65', name: 'Singapore' },
      { code: '+66', name: 'Thailand' },
      { code: '+81', name: 'Japan' },
      { code: '+82', name: 'South Korea' },
      { code: '+84', name: 'Vietnam' },
      { code: '+86', name: 'China' },
      { code: '+591', name: 'Bolivia' },
      { code: '+506', name: 'Costa Rica' },
      { code: '+593', name: 'Ecuador' },
      { code: '+503', name: 'El Salvador' },
      { code: '+33', name: 'France' },
      { code: '+49', name: 'Germany' },
      { code: '+30', name: 'Grece' },
      { code: '+502', name: 'Guatemala' },
      { code: '+504', name: 'Honduras' },
      { code: '+39', name: 'Italia' },
      { code: '+507', name: 'Panama' },
      { code: '+595', name: 'Paraguay' },
      { code: '+351', name: 'Portugal' },
      { code: '+7', name: 'Russia' },
      { code: '+966', name: 'Saudi Arabia' },
      { code: '+27', name: 'South Africa' },
      { code: '+34', name: 'España' },
      { code: '+598', name: 'Uruguay' }

]